name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build capacitor-android
      run: docker build . --file build/capacitor-android/Dockerfile --tag fischer-matthias/capacitor-android:$(date +%s)
